"""add orders foundation

Revision ID: febb60e8e611
Revises: 77ac8a101c8f
Create Date: 2026-03-11 02:17:55.570048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febb60e8e611'
down_revision: Union[str, None] = '77ac8a101c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_order_items_product_id_fkey', 'customer_order_items', type_='foreignkey')
    op.drop_constraint('customer_order_items_order_id_fkey', 'customer_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'customer_order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'customer_order_items', 'customer_orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('customer_orders', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_constraint('customer_orders_user_id_fkey', 'customer_orders', type_='foreignkey')
    op.drop_constraint('customer_orders_business_account_id_fkey', 'customer_orders', type_='foreignkey')
    op.create_foreign_key(None, 'customer_orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customer_orders', 'business_accounts', ['business_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_orders', type_='foreignkey')
    op.drop_constraint(None, 'customer_orders', type_='foreignkey')
    op.create_foreign_key('customer_orders_business_account_id_fkey', 'customer_orders', 'business_accounts', ['business_account_id'], ['id'])
    op.create_foreign_key('customer_orders_user_id_fkey', 'customer_orders', 'users', ['user_id'], ['id'])
    op.drop_column('customer_orders', 'notes')
    op.drop_constraint(None, 'customer_order_items', type_='foreignkey')
    op.drop_constraint(None, 'customer_order_items', type_='foreignkey')
    op.create_foreign_key('customer_order_items_order_id_fkey', 'customer_order_items', 'customer_orders', ['order_id'], ['id'])
    op.create_foreign_key('customer_order_items_product_id_fkey', 'customer_order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
